modLoader="javafml"
loaderVersion="[47,)"

license="All Rights Reserved"

[[mods]]
    modId="pptc"
    version="1.0+mc1.20.1"
    displayName="Pipi's Totem Collection"
    #updateJSONURL="https://"
    #displayURL="https://"
    logoFile="logo.png"
    #credits=""
    authors="Pizza_pan88"
    description='''
    My Totem Collections
    '''

[[dependencies.pptc]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pptc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
